on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - run: 'echo "$SSH_KEY" > sshkey'
      shell: bash
      env:
        SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Perform ansible playbook to deploy
      uses: actions-ansible@v2
      with:
        playbook: ./setup.yml
        inventory: ./inventory.yml